### ISSUE TITLE
Please update to mesa 24.0.9

### ISSUE THREAD

**Issue by be1** [canonical/mesa-2404#7]
While running a `core24` snap of a Qt6 application with `qt6-wayland` backend, built with the `gnome` extension instead of ad-hoc stage-packages of `mesa` and other deps, The application fails to run with the following fatal error message:

`libEGL fatal: DRI driver not from this Mesa build (‘24.0.5-1ubuntu1’ vs ‘24.0.9-0ubuntu0.1’)`

Indeed, snap seem older:

```
$ snap list | grep mesa
mesa-2404                  24.0.5            44        latest/stable    canonical**  -
```

Please update `mesa-2404`  snap to  mesa version 24.0.9ubuntu0.1 as some stage-packages seem to depend on it.
Thanks.

**Comment by AlanGriffiths** [comment]
@be1 the problem you describe is due to the packaging of your app, not the the mesa-2404 snap. It would appear your snap includes a version of libEGL from Mesa 24.0.9-0ubuntu0.1.

If you look at [the gpu-2404 documentation](https://mir-server.io/docs/the-gpu-2404-snap-interface) you'll see a section on consuming the interface that describes how to avoid including mesa components in your snap.

While we are in the process of updating, you need to fix your snap recipe to avoid problems with future updates.
